version: '3.7'
services:
  db:
    image: postgres:11
    ports:
      - '54320:5432'
    networks:
      hmdanet:
        ipv4_address: 172.19.0.2
  spark:
    image: ewalsh200/toyspark:latest
    ports:
      - '8080:8080'
    networks:
      hmdanet:
        ipv4_address: 172.19.0.3


networks:
  hmdanet:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
